[workspace]
members = [
    "cli",
    "discovery",
    "soap",
    "wsdl",
    "onvif"
]

[workspace.package]
version = "0.1.0"
authors = ["Shehriyar Qureshi <thatdevsherry@gmail.com>"]
description = "ONVIF implementation in Rust"
edition = "2021"