on:
  push:
    branches:
      - main

name: CI

jobs:
  build:
    name: onvif-rs on armv7
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install libssl-dev -y # reqwest fails on ssl

      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf
